services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    expose:
      - ${PORT}
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: ${PORT}
    # volumes:
    #   - ../:/usr/src/app

